### PR TITLE
Split up core.py

### PR DESCRIPTION
**Pull request by mhsmith**
So far I've moved the Property classes into a module of their own, and completely decoupled them and their tests from Component, and even from PyScript itself. 

Unit tests all pass, but I haven't checked the builder yet.

I haven't committed the ZIPs, because I'm not sure what the plan is to deal with them. Shouldn't they be .gitignored? Updating them with every commit will rapidly inflate the size of the repository.

I also haven't updated src/pyscript.toml, because it's already way out of date with the source files list. Does anything use it?

TBD:
* Make sure the builder still works.
* Move Row, Column and Grid into individual files under `invent.ui.containers`.

### CODE REVIEW

**Comment by ntoll** [comment]
Aha..! Nice work @mhsmith - I had splitting up `core.py` on my todo list for today. Since you have this in flight already, I'll not start that work until we've had a chat in tomorrow's pairing session. :+1:

**Comment by ntoll** [comment]
FWIW, I had in mind to create a new `core` directory in which would be found the various source files, from which the `__initi__` would reference the classes/objects we hoped to export via `__all__` in the `invent.ui.core` module. :+1:

But, as always, anything I say or suggest is always open for discussion and feedback. Ideas most welcome.

**Comment by mhsmith** [comment]
> I had in mind to create a new `core` directory in which would be found the various source files, , from which the __init__ would reference the classes/objects

That makes sense, and it reduces the number of other files that need to be updated. I've done that, and also moved Page, Row, Column and Grid into a `containers` package.

The unit tests all pass, and the builder still works as it did before, as far as I can see.

**Review by ntoll — APPROVED** [review]
:shipit:

**Pull request merged**
